sudo: false
language: ruby
cache: bundler
rvm:
  - '2.2.1'
  - '2.2.3'
  - '2.3.0'

services:
  - redis-server

before_script:
  - bundle exec ruby spec/integration/support/run_all.rb &
  - sleep 2

script:
  - bundle exec rspec --exclude-pattern "spec/integration/*"
  - bundle exec rspec spec/integration
