sudo: false
language: ruby
cache: bundler

services:
  - redis-server

gemfile:
  - gemfiles/rails_4.gemfile
  - Gemfile

rvm:
  - '2.5.1'
  - '2.4.4'

before_script:
  - bundle exec ruby spec/integration/support/run_all.rb &
  - sleep 2

script:
  - bundle exec rspec --exclude-pattern "spec/integration/*"
  - bundle exec rspec spec/integration
